version: 2.1
jobs:
  build:
    steps:
      - checkout
      - run:
          name: Push to Docker Hub
          command: |
          
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin 

            services=("reverseproxy" "backend_user" "backend_feed" "frontend")

            for service in "${services[@]}"; do
                docker-compose -f docker-compose-build.yaml build $service
                docker tag $service $DOCKER_USERNAME/$service
                docker push $DOCKER_USERNAME/$service
            done

            docker logout

workflows:
  version: 2
  build:
    jobs:
      - build
