version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Push to Docker Hub
          command: |

            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin 

            services=("reverseproxy" "backend_user" "backend_feed" "frontend")


            for service in "${services[@]}"; do
                image_id=$(docker-compose -f docker-compose-build.yaml images -q $service)

                if [ -n "$image_id" ]; then
                    docker tag $image_id $DOCKER_USERNAME/$service
                    docker push $DOCKER_USERNAME/$service
                else
                    echo "Không tìm thấy image ID cho dự án $service"
                fi
            done
            docker logout

workflows:
  version: 2
  build:
    jobs:
      - build
