version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Build all and tag
          command: |

            docker build -t udagram-reverseproxy ./udagram-reverseproxy
            docker tag udagram-reverseproxy $DOCKER_USERNAME/udagram-reverseproxy

            docker build -t udagram-api-user ./udagram-api-user
            docker tag udagram-api-user $DOCKER_USERNAME/udagram-api-user

            docker build -t udagram-api-feed ./udagram-api-feed
            docker tag udagram-api-feed $DOCKER_USERNAME/udagram-api-feed

            docker build -t udagram-frontend ./udagram-frontend
            docker tag udagram-frontend $DOCKER_USERNAME/udagram-frontend
      
      - run: 
          name: Authentication
          command: |

            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin 
      - run: 
          name: Push to DockerHub
          command: |
            docker push $DOCKER_USERNAME/udagram-reverseproxy

            docker push $DOCKER_USERNAME/udagram-api-user

            docker push $DOCKER_USERNAME/udagram-api-feed

            docker push $DOCKER_USERNAME/udagram-frontend
      - run: 
          name: Log out
          command: |
            docker logout

workflows:
  version: 2
  build:
    jobs:
      - build
